GET http://localhost:5144/todos

###

POST http://localhost:5144/todos
content-type: application/json

{
    "id": 1,
    "name": "Write another demo",
    "dueDate": "2025-12-31",
    "isCompleted": false
}

###
GET http://localhost:5144/todos/2

###
DELETE http://localhost:5144/todos/2

###
GET http://localhost:5144/tasks/1